[package]
name = "imagelink"
version = "0.1.0"
authors = ["Phil Shafer <phil@>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
kamadak-exif = "0.5.2"
snafu = "0.6"
lazy_static = "*"
regex = "*"
